#!/usr/bin/env bash
set -euo pipefail
jq -r '. | "\(.name) \(.types[0].type.name) \(.weight) \(.height)"' data.json | \
awk '{name=$1; type=$2; weight=$3/10; height=$4/10; \
printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", name, type, weight, height}' | \
sed 's/\b\(.\)/\u\1/; s/\b\(.\)\(.*type \)\(.\)/\1\2\u\3/'
