#!/usr/bin/env bash
set -euo pipefail
NAME=$(jq -r '.name' data.json); TYPE=$(jq -r '.types[0].type.name' data.json); HEIGHT=$(jq -r '.height/10' data.json); WEIGHT=$(jq -r '.weight/10' data.json); echo "${NAME^} is of type ${TYPE^}, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
